name: CI

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
      - master
      - develop
      
jobs:
  test:
    name: UnitTest
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle 
        run: ./gradlew build
        
      - name: Unit tests 
        id: tests
        run: ./gradlew test
        
       # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: build/test-results/**/*.xml
