name: CI

on:

  pull_request_target:
    branches:
      - master
      - develop
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Unit test
        run: ./gradlew test

      - name: Test Success
        if: success()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{github.event.number}}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "테스트 모두 통과!",
              event: "APPROVE"
            })
            
      - name: Test Fail
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{github.event.number}}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "테스트 코드 실패.. 다시 작성해 주세요.",
             event: "REQUEST_CHANGES"
            })

      - name: Ktlint
        run: ./gradlew ktlint

      - name: Lint Success
        if: success()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{github.event.number}}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "이쁜 코드군요..!",
              event: "APPROVE"
            })
      - name: Lint Fail
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{github.event.number}}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "lint 정도는 하고 올립시다~",
              event: "REQUEST_CHANGES"
            })
