name: CI

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
      - master
      - develop
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Unit test
        run: ./gradlew test

      - name: Ktlint
        run: ./gradlew ktlint
        
      - name: Unit test
        run: ./gradlew test
